services:
  phon:
    image: phon:latest
    container_name: phon
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - /Users/chuazhou/dev/log-viewer/logs:/home/pyuser/phon/logs
      - /Users/chuazhou/dev/pyphon/config:/home/pyuser/phon/config
      - /Users/chuazhou/dev/pyphon/pyphon:/home/pyuser/phon/pyphon
      - /Users/chuazhou/dev/pyphon/web:/home/pyuser/phon/web
      - /Users/chuazhou/dev/pyphon/phon.py:/home/pyuser/phon/phon.py
    ports:
      - "5888:5888"
    restart: unless-stopped


